machine:
  python:
    version: 3.6.1
  environment:
    FLASK_APP: run.py
    SECRET: Testing
    APP_SETTTINGS: development
    DATABASE_URL: postgresql://localhost/buckets
    
dependencies:
  post:
    - pip install -r requirements.txt

test:
  override:
    - createdb;
    - createdb;
    - rm -rf migrations
    - python manage.py db init
    - python manage.py db migrate
    - python manage.py db upgrade
    - nosetests -v