"""empty message

Revision ID: 66eeaa39d47d
Revises: 
Create Date: 2017-05-20 12:53:29.844397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eeaa39d47d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlists', 'users', ['user_id'], ['id'])
    op.drop_column('bucketlists', 'user_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'user_id')
    # ### end Alembic commands ###
