"""empty message

Revision ID: 895d4b87e0ce
Revises: 10ccc57a5ace
Create Date: 2017-05-17 12:35:07.765310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '895d4b87e0ce'
down_revision = '10ccc57a5ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=256), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'date_registered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
