"""empty message

Revision ID: 912fd4565852
Revises: 66eeaa39d47d
Create Date: 2017-05-20 17:45:56.846479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912fd4565852'
down_revision = '66eeaa39d47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlistsitems_bucketlist_id_fkey', 'bucketlistsitems', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlistsitems', 'bucketlists', ['bucketlist_id'], ['bucketlist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlistsitems', type_='foreignkey')
    op.create_foreign_key('bucketlistsitems_bucketlist_id_fkey', 'bucketlistsitems', 'bucketlists', ['bucketlist_id'], ['id'])
    # ### end Alembic commands ###
