"""empty message

Revision ID: a5a9ac1f2d04
Revises: c42f8ec0fa4a
Create Date: 2017-05-17 11:12:45.500041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a9ac1f2d04'
down_revision = 'c42f8ec0fa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('bucketlist_id', sa.Integer(), nullable=True))
    op.add_column('bucketlistsitems', sa.Column('item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlistsitems', 'item_id')
    op.drop_column('bucketlists', 'bucketlist_id')
    # ### end Alembic commands ###
