"""empty message

Revision ID: ba2482fecda1
Revises: df82fb3ccdd0
Create Date: 2017-05-16 12:58:09.373950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2482fecda1'
down_revision = 'df82fb3ccdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlistsitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('bucketlits_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlits_id'], ['bucketlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlistsitems')
    # ### end Alembic commands ###
