"""empty message

Revision ID: c42f8ec0fa4a
Revises: ba2482fecda1
Create Date: 2017-05-16 16:13:03.938451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42f8ec0fa4a'
down_revision = 'ba2482fecda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistsitems', sa.Column('bucketlist_id', sa.Integer(), nullable=True))
    op.drop_constraint('bucketlistsitems_bucketlits_id_fkey', 'bucketlistsitems', type_='foreignkey')
    op.create_foreign_key(None, 'bucketlistsitems', 'bucketlists', ['bucketlist_id'], ['id'])
    op.drop_column('bucketlistsitems', 'bucketlits_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistsitems', sa.Column('bucketlits_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bucketlistsitems', type_='foreignkey')
    op.create_foreign_key('bucketlistsitems_bucketlits_id_fkey', 'bucketlistsitems', 'bucketlists', ['bucketlits_id'], ['id'])
    op.drop_column('bucketlistsitems', 'bucketlist_id')
    # ### end Alembic commands ###
